2022-03-10 10:49:34,308 web.py[line:1789] ERROR Uncaught exception GET /login/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/login/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
TypeError: object str can't be used in 'await' expression
2022-03-10 10:49:34,329 web.py[line:2239] ERROR 500 GET /login/ (127.0.0.1) 21.39ms
2022-03-10 10:51:44,463 login_views.py[line:32] ERROR 验证码错误: '10086'
2022-03-10 10:51:52,696 web.py[line:1789] ERROR Uncaught exception POST /login/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/login/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/qiangchen/Desktop/Labs/Sao/views/login/login_views.py", line 46, in post
    user_json = json_encode(ex_user)
  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/tornado/escape.py", line 75, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
2022-03-10 10:51:52,729 web.py[line:2239] ERROR 500 POST /login/ (127.0.0.1) 83.62ms
2022-03-10 10:53:31,229 web.py[line:1789] ERROR Uncaught exception POST /login/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/login/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/qiangchen/Desktop/Labs/Sao/views/login/login_views.py", line 46, in post
    user_json = json_encode(ex_user)
  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/tornado/escape.py", line 75, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
2022-03-10 10:53:31,235 web.py[line:2239] ERROR 500 POST /login/ (127.0.0.1) 16.06ms
2022-03-10 11:04:21,277 web.py[line:1789] ERROR Uncaught exception POST /login/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/login/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/qiangchen/Desktop/Labs/Sao/views/login/login_views.py", line 48, in post
    self.http_response(conf.base.ERROR_CODE_0, {'user': user_json, 'token': token})
  File "/Users/qiangchen/Desktop/Labs/Sao/views/base/base_views.py", line 11, in http_response
    self.write(json.dumps({'msg': error.msg, 'code': error.code, 'data': data}))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
2022-03-10 11:04:21,292 web.py[line:2239] ERROR 500 POST /login/ (127.0.0.1) 27.74ms
2022-03-10 11:11:16,002 web.py[line:1789] ERROR Uncaught exception POST /login/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/login/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/qiangchen/Desktop/Labs/Sao/views/login/login_views.py", line 46, in post
    user_json = ex_user.to_json()
  File "/Users/qiangchen/Desktop/Labs/Sao/models/base_model.py", line 11, in to_json
    for key, value in self.__table__.columns:
  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/sqlalchemy/sql/operators.py", line 434, in __getitem__
    return self.operate(getitem, index)
  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 861, in operate
    return op(self.comparator, *other, **kwargs)
  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/sqlalchemy/sql/operators.py", line 434, in __getitem__
    return self.operate(getitem, index)
  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 76, in operate
    return o[0](self.expr, op, *(other + o[1:]), **kwargs)
  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/sqlalchemy/sql/default_comparator.py", line 177, in _getitem_impl
    _unsupported_impl(expr, op, other, **kw)
  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/sqlalchemy/sql/default_comparator.py", line 181, in _unsupported_impl
    raise NotImplementedError(
NotImplementedError: Operator 'getitem' is not supported on this expression
2022-03-10 11:11:16,019 web.py[line:2239] ERROR 500 POST /login/ (127.0.0.1) 25.61ms
2022-03-10 11:11:46,673 web.py[line:1789] ERROR Uncaught exception POST /login/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/login/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/qiangchen/Desktop/Labs/Sao/views/login/login_views.py", line 46, in post
    user_json = ex_user.to_json()
  File "/Users/qiangchen/Desktop/Labs/Sao/models/base_model.py", line 11, in to_json
    for key, value in self.__table__.columns.items:
TypeError: 'method' object is not iterable
2022-03-10 11:11:46,681 web.py[line:2239] ERROR 500 POST /login/ (127.0.0.1) 22.53ms
2022-03-10 11:12:04,854 web.py[line:1789] ERROR Uncaught exception POST /login/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/login/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/qiangchen/Desktop/Labs/Sao/views/login/login_views.py", line 48, in post
    self.http_response(conf.base.ERROR_CODE_0, {'user': user_json, 'token': token})
  File "/Users/qiangchen/Desktop/Labs/Sao/views/base/base_views.py", line 11, in http_response
    self.write(json.dumps({'msg': error.msg, 'code': error.code, 'data': data}))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Column is not JSON serializable
2022-03-10 11:12:04,865 web.py[line:2239] ERROR 500 POST /login/ (127.0.0.1) 18.23ms
2022-03-10 11:38:56,121 web.py[line:1789] ERROR Uncaught exception POST /login/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/login/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/qiangchen/Desktop/Labs/Sao/views/login/login_views.py", line 36, in post
    ex_user = User.query.filter(phone=phone).first()
TypeError: filter() got an unexpected keyword argument 'phone'
2022-03-10 11:38:56,138 web.py[line:2239] ERROR 500 POST /login/ (127.0.0.1) 24.09ms
