2022-03-23 14:20:28.335 | ERROR    | conf.logger:log_request_error:16 - uid: '', requst: HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/v1/login/', version='HTTP/1.1', remote_ip='127.0.0.1'), query: '', body b'{\n    "phone": "18856931381",\n    "password": "chenzhima"\n}'
Traceback (most recent call last):

  File "/Users/qiangchen/Desktop/Labs/Sao/venv/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             │       │    │            │    └ {}
             │       │    │            └ <views.login.login_views.LoginHandler object at 0x7fc5319f4eb0>
             │       │    └ []
             │       └ <views.login.login_views.LoginHandler object at 0x7fc5319f4eb0>
             └ <bound method LoginHandler.post of <views.login.login_views.LoginHandler object at 0x7fc5319f4eb0>>

  File "/Users/qiangchen/Desktop/Labs/Sao/views/login/login_views.py", line 22, in post
    self._login_with_password(phone, password)
    │    │                    │      └ 'chenzhima'
    │    │                    └ '18856931381'
    │    └ <function LoginHandler._login_with_password at 0x7fc5319cd310>
    └ <views.login.login_views.LoginHandler object at 0x7fc5319f4eb0>

  File "/Users/qiangchen/Desktop/Labs/Sao/views/login/login_views.py", line 39, in _login_with_password
    self._login_success(user)
    │    │              └ <models.user_model.User object at 0x7fc531a8ab20>
    │    └ <function LoginHandler._login_success at 0x7fc5319cd430>
    └ <views.login.login_views.LoginHandler object at 0x7fc5319f4eb0>

  File "/Users/qiangchen/Desktop/Labs/Sao/views/login/login_views.py", line 60, in _login_success
    self.success({'user': user_json, 'token': token})
    │    │                │                   └ 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsImV4cCI6MTY0ODEwMjgyOH0.aWjTXEpXiSorh7WdGu9NZxxqT9zHopAT0ctrBqhw2gA'
    │    │                └ {'id': 1, 'phone': '18856931381', 'password': b'\xb4\x89\xf9Qh\xcfK\x8b:P\x0c:b\x1a\x8f\xe0\x16\x01=J\xed\x190\xdc\xa3@8^\x9f...
    │    └ <function BaseHandler.success at 0x7fc5319d1f70>
    └ <views.login.login_views.LoginHandler object at 0x7fc5319f4eb0>

  File "/Users/qiangchen/Desktop/Labs/Sao/views/base/base_views.py", line 37, in success
    self.finish(json.dumps({'msg': ERROR_CODE_0.msg, 'code': ERROR_CODE_0.code, 'data': data}))
    │    │      │    │             │            │            │            │             └ {'user': {'id': 1, 'phone': '18856931381', 'password': b'\xb4\x89\xf9Qh\xcfK\x8b:P\x0c:b\x1a\x8f\xe0\x16\x01=J\xed\x190\xdc\x...
    │    │      │    │             │            │            │            └ 0
    │    │      │    │             │            │            └ SaoException('ok', 0)
    │    │      │    │             │            └ 'ok'
    │    │      │    │             └ SaoException('ok', 0)
    │    │      │    └ <function dumps at 0x7fc530acbb80>
    │    │      └ <module 'json' from '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py'>
    │    └ <function RequestHandler.finish at 0x7fc530d8aee0>
    └ <views.login.login_views.LoginHandler object at 0x7fc5319f4eb0>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           │                │      └ {'msg': 'ok', 'code': 0, 'data': {'user': {'id': 1, 'phone': '18856931381', 'password': b'\xb4\x89\xf9Qh\xcfK\x8b:P\x0c:b\x1a...
           │                └ <function JSONEncoder.encode at 0x7fc530acba60>
           └ <json.encoder.JSONEncoder object at 0x7fc530a73af0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
             │    │          └ {'msg': 'ok', 'code': 0, 'data': {'user': {'id': 1, 'phone': '18856931381', 'password': b'\xb4\x89\xf9Qh\xcfK\x8b:P\x0c:b\x1a...
             │    └ <function JSONEncoder.iterencode at 0x7fc530acbaf0>
             └ <json.encoder.JSONEncoder object at 0x7fc530a73af0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
           │           └ {'msg': 'ok', 'code': 0, 'data': {'user': {'id': 1, 'phone': '18856931381', 'password': b'\xb4\x89\xf9Qh\xcfK\x8b:P\x0c:b\x1a...
           └ <_json.Encoder object at 0x7fc531aa61c0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

TypeError: Object of type bytes is not JSON serializable
